// <auto-generated />
using System;
using BlogEngine.DataModels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogEngine.DataModels.Migrations
{
    [DbContext(typeof(BlogEngineDatabaseContext))]
    [Migration("20251104205156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BlogEngine.DataModels.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("comment_content");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_user_id");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_delete");

                    b.Property<Guid?>("ParrentCommentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parrent_comment_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("UpdatedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("BlogEngine.DataModels.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_user_id");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_delete");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("post_content");

                    b.Property<string>("SlugTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug_title");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("UpdatedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("BlogEngine.DataModels.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_delete");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("UpdatedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BlogEngine.DataModels.Models.Comment", b =>
                {
                    b.HasOne("BlogEngine.DataModels.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_comment_post");

                    b.HasOne("BlogEngine.DataModels.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_comment_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogEngine.DataModels.Models.Post", b =>
                {
                    b.HasOne("BlogEngine.DataModels.Models.User", "CreatedUser")
                        .WithMany("Posts")
                        .HasForeignKey("CreatedUserId")
                        .IsRequired()
                        .HasConstraintName("FK_post_User");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("BlogEngine.DataModels.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogEngine.DataModels.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
